#!/usr/bin/env bash
# Install dependencies, build Emacs and VTerm.

set -euo pipefail
IFS=$'\n\t'

base="$HOME/.emacs.d/src"

required=(autoconf texinfo libxml2 imagemagick librsvg gnutls gnupg libvterm)
required_casks=(mactex)

heading() {
  printf "\033[38;5;013m %s  \033[0m  \n" "$*"
}

contains() {
	local e match="$1"
	shift
	for e; do [[ "$e" == "$match" ]] && return 0; done
	return 1
}

heading "Installing Dependencies..."

# Ensure the given homebrew packages are installed and up to date
brew_ensure() {
  # Decide if we are operating on 'brew' or 'brew cask'
  prefix="brew "
  [ "$1" = "cask" ] && prefix="${prefix}cask " && shift

  # Get list of missing packages, install them
  read -r -a installed < <(eval $prefix list -1)
  required=("$@")
  missing=()
  for p in "${required[@]}"; do
	  contains "$p" "${installed[@]}" || needed+=("$p")
  done
  if [ -n "${missing[*]}" ]; then
	  echo "Installing packages: ${missing[*]}"
	  $prefix install "${missing[@]}"
  fi

  # Get list of outdated packages, upgrade them
  outdated="$(eval $prefix outdated | awk '{print $1}')"
  upgrade=()
  for p in "${required[@]}"; do
	  contains "$p" "${outdated[@]}" && upgrade+=("$p")
  done
  if [ -n "${upgrade[*]}" ]; then
	  echo "Upgrading packages: ${upgrade[*]}"
	  $prefix upgrade "${upgrade[@]}"
  fi
}

brew_ensure "${required[@]}"
brew_ensure cask "${required_casks[@]}"

mkdir -p "$base"
pushd "$base"

[ -d "./emacs" ] || git clone "https://git.savannah.gnu.org/git/emacs.git"
pushd "./emacs"

heading "Building Emacs..."

git pull
git reset HEAD --hard
./autogen.sh
# The ctags bit is to rename the ctags binary so it doesn't conflict with an
# existing, non-emacs ctags installation
./configure --without-dbus --without-pop --with-gnutls --with-ns --disable-ns-self-contained --with-rsvg --with-imagemagick --with-json --with-xml2 --with-modules CFLAGS='-Ofast -march=native -pipe -falign-functions=64 -fomit-frame-pointer -funit-at-a-time -fforce-addr -mfpmath=sse -ffast-math -fno-finite-math-only -fstack-check -I /usr/local/opt/libxml2/include/libxml2' --program-transform-name='s/^ctags$/ctags.emacs/'
# Even though we move the binary ourselves, we still need to install to get the
# Emacs Lisp source in the right place.
make install
rm -rf "$HOME/Applications/Emacs.app"
mv nextstep/Emacs.app "$HOME/Applications/"

popd

[ -d "./emacs-libvterm" ] || git clone "https://github.com/akermu/emacs-libvterm.git"
pushd "./emacs-libvterm"

heading "Building VTerm..."

git pull
git reset HEAD --hard
mkdir -p build
cd build
cmake ..
make

popd
